# Generated by Django 3.2.17 on 2023-02-08 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whats_my_status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountspent',
            old_name='time',
            new_name='updatedOn',
        ),
        migrations.RemoveField(
            model_name='timespent',
            name='minutes',
        ),
        migrations.AddField(
            model_name='amountspent',
            name='property',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timespent',
            name='property',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timespent',
            name='updatedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amountspent',
            name='amountSpentOn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timespent',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timespent',
            name='timeSpentOn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
