# Generated by Django 3.2.17 on 2023-02-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_my_status', '0002_auto_20230208_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountspent',
            name='updatedOn',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timespent',
            name='updatedOn',
            field=models.DateField(auto_now_add=True),
        ),
    ]
